In [1]:
import pysimpactcyan
from psimapacthelper import *
simpact = pysimpactcyan.PySimpactCyan()

Warning: can't seem to find the simpact data directory
Warning: can't seem to find a way to run the simpact executables

In [3]:
cfg = { "population.nummen": 500,
        "population.numwomen": 500,
        "population.simtime":20,
        "diagnosis.baseline": -99999,
        "monitoring.cd4.threshold":1,
        "hivtransmission.param.a":-1.3,
        "hivtransmission.param.b":-90,
        "hivtransmission.param.c":0.5,
        "conception.alpha_base": -2.9,
        "dissolution.alpha_0": -2.50494307,
        "population.agedistfile": "/home/jupyter/who-aids-prop/build/python/eswatini_1980.csv",
        "periodiclogging.interval": 0.25
        }

art_intro = {
        "time": 10, #around 2000
        "diagnosis.baseline": -1.75,
        "monitoring.cd4.threshold": 500
    }

baseline_results = simpact.run(
        config=cfg,
        destDir='data',
        seed=1234,
        quiet=True,
        identifierFormat='baseline'
    )

art_results = simpact.run(
        config=cfg,
        interventionConfig=[art_intro],
        destDir='data',
        seed=1234,
        quiet=True,
        identifierFormat='art'
    )

In [4]:
baseline_datalist = readthedata(baseline_results)
art_datalist = readthedata(art_results)

In [5]:
evaluation_timepoints_inc = np.arange(0, 19.0, 1.0)

In [6]:
baseline_dfs = []
for timepoint in evaluation_timepoints_inc:
        timewindow = [timepoint, timepoint+1]
        result_df = incidence_calculator(datalist=baseline_datalist, agegroup=[15,50],timewindow=timewindow)
        result_df['timepoint'] = timepoint

        # Append the resulting dataframe to the list
        baseline_dfs.append(result_df)

baseline_dfs = pd.concat(baseline_dfs, ignore_index=True)
incidence_wide_df = baseline_dfs.pivot(index='timepoint', columns='Gender', values='incidence').reset_index()
incidence_wide_df.columns.name = None  # Remove the name of the columns index
incidence_wide_df

    timepoint         0         1     Total
0         0.0  0.000000  0.000000  0.000000
1         1.0  0.011178  0.000000  0.005671
2         2.0  0.016031  0.005480  0.010822
3         3.0  0.010195  0.005181  0.007709
4         4.0  0.014468  0.000000  0.007380
5         5.0  0.004673  0.019014  0.011782
6         6.0  0.027345  0.031955  0.029648
7         7.0  0.022964  0.008900  0.015821
8         8.0  0.018321  0.017561  0.017933
9         9.0  0.017912  0.012928  0.015372
10       10.0  0.026094  0.016403  0.021106
11       11.0  0.004210  0.007735  0.006048
12       12.0  0.008052  0.015343  0.011786
13       13.0  0.003887  0.030444  0.017307
14       14.0  0.007307  0.007175  0.007241
15       15.0  0.007158  0.017840  0.012507
16       16.0  0.014784  0.011040  0.012908
17       17.0  0.007473  0.018487  0.013009
18       18.0  0.011232  0.014606  0.012940

In [7]:
art_dfs = []
for timepoint in evaluation_timepoints_inc:
        timewindow = [timepoint, timepoint+1]
        result_df = incidence_calculator(datalist=art_datalist, agegroup=[15,50],timewindow=timewindow)
        result_df['timepoint'] = timepoint

        # Append the resulting dataframe to the list
        art_dfs.append(result_df)

art_dfs = pd.concat(art_dfs, ignore_index=True)
incidence_wide_df_art = art_dfs.pivot(index='timepoint', columns='Gender', values='incidence').reset_index()
incidence_wide_df_art.columns.name = None  # Remove the name of the columns index
incidence_wide_df_art

    timepoint         0         1     Total
0         0.0  0.000000  0.000000  0.000000
1         1.0  0.011178  0.000000  0.005671
2         2.0  0.010662  0.000000  0.005397
3         3.0  0.010156  0.010330  0.010242
4         4.0  0.014407  0.005028  0.009825
5         5.0  0.018688  0.004730  0.011751
6         6.0  0.009154  0.009001  0.009077
7         7.0  0.022742  0.026275  0.024542
8         8.0  0.018086  0.013057  0.015524
9         9.0  0.035761  0.012842  0.024053
10       10.0  0.013060  0.016181  0.014678
11       11.0  0.008382  0.019433  0.014115
12       12.0  0.020310  0.007693  0.013830
13       13.0  0.019746  0.011264  0.015398
14       14.0  0.007451  0.000000  0.003628
15       15.0  0.014623  0.006960  0.010697
16       16.0  0.030523  0.003540  0.016526
17       17.0  0.023322  0.028506  0.026027
18       18.0  0.023259  0.010742  0.016752